# Generated by Django 4.2 on 2023-05-04 14:26

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[categories.models.slug_length_validation]),
        ),
    ]
